version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/sdk/python"
      - "/services/maxwell/reference/python"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directories:
      - "/sdk/typescript"
      - "/services/maxwell/reference/examples/express-middleware"
      - "/services/maxwell/reference/javascript"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
